FS-28 update css override documentation
palantirnet/search_api_federated_solr pull request #103
Opened 2020-02-15 01:01 UTC by biz123

2020-02-19 16:46 UTC, agentrickard requested changes
Looks fine except I don't understand why closing braces aren't on a new line anymore.

2020-02-19 16:46 UTC, agentrickard commented on docs/assets/search_theme_override.css
> +  background-color: #f6f6f6; }
Is this the new style standard? To have the closing brace on the same line?

2020-02-24 16:45 UTC, biz123 commented on docs/assets/search_theme_override.css
> +  background-color: #f6f6f6; }
That is curious. It was compiled using the toolset on the react app. I will look at how that was set up.

2020-02-24 17:00 UTC, biz123 commented on docs/assets/search_theme_override.css
> +  background-color: #f6f6f6; }
Since the intent here is really a template for someone not compiling SASS but editing CSS directly I should not have used compiled CSS. I will review/update this to more user-friendly and will revert those braces.

2020-02-24 18:31 UTC, agentrickard commented
I have a semi-related question.

When changing the CSS, are we now using `fs-root` as the base ID of the application? 

If so, that has cascading effects throughout the application.

2020-02-24 20:30 UTC, biz123 commented
> I have a semi-related question.
> 
> When changing the CSS, are we now using `fs-root` as the base ID of the application?
> 
> If so, that has cascading effects throughout the application.

I can address that here.

2020-02-24 20:53 UTC, agentrickard commented
We now have to go into the actual React code and change that, too. I wasn't sure if you had done that when you updated the CSS.

See, for instance,  https://github.com/palantirnet/federated-search-react/blob/2.x/src/index.js#L163

2020-02-24 21:43 UTC, biz123 commented
@agentrickard I have updated the CSS and SASS with some code cleanup. I also updated the main app ID in the template in templates/search-app.html.twig and related documentation.

2020-03-05 22:51 UTC, biz123 commented
I just reviewed this again to make sure no updates are needed after completing and merging https://github.com/palantirnet/federated-search-react/pull/62
...And this still works with latest updates so it is ready for review.

2020-03-10 14:51 UTC, agentrickard commented
I rolled a 3.0.0-beta1 version of the app and will include it here for testing.

2020-03-10 15:16 UTC, agentrickard commented
When I test this in Drupal 8, I get a flash of unstyled content, which looks like the JS hasn't fully loaded.

This did not happen in the Alpha1 release, so I wonder if it's a CSS issue?

See https://drive.google.com/file/d/1UlcCjkrmhXwGkS5f7OBXvLAHz-44sfvM/view?usp=sharing

2020-03-10 15:20 UTC, agentrickard commented
Gif version

![Untitled](https://user-images.githubusercontent.com/360988/76328020-23612280-62c1-11ea-81ea-20e646d516e2.gif)

2020-03-12 15:14 UTC, agentrickard commented
I tried reverting https://github.com/palantirnet/federated-search-react/pull/62/commits/3d93f2acb2c6c5c852b419782e070fb2f8b20c43 and rolling a beta2 release.

I still get a flash of the JS message.

2020-03-12 21:26 UTC, nstriedinger commented
The issue:
![Screen Shot 2020-03-12 at 5 17 03 PM](https://user-images.githubusercontent.com/231467/76568082-864fe680-6486-11ea-9b96-e22ee4b9a2af.png)

2020-03-13 13:45 UTC, merged

2020-03-13 13:46 UTC, agentrickard commented
We need to apply these changes to the 7.x version, which I can do today.