Root 863 compute site specific urls
palantirnet/search_api_federated_solr pull request #83
Opened 2019-03-27 17:41 UTC by jesconstantine

This PR updates the proxy + autocomplete config for the block and search app, making it more config_split friendly.  Namely, the module will now compute urls at block + search app route render instead of on config submission.

It also updates the install config, schema, and update hook accordingly.

## To test the update hook respects prior custom endpoints

### Pull the demo site branch to get latest changes
1. From the `federated-search-demo` check out and pull `root-198-search-terms-field` (I think you made the last changes anyway)

### Check out v2.0 of the module for the site
1. Check out the`8.x-2.0` tag in `search_api_federated_solr`
    1. From your host machine, in the project root: `cd src/search_api_federated_solr`
	1. Fetch or pull down updates from origin
	1. Check out `8.x-2.0` tag (git will tell you that you're in a detached head state, that's ok)

### Rebuild the site (resets the database from any prior testing of the update hook for 8.x-2.1)
1. Rebuild the d8 standalone site from within the project root on the VM `phing install-d8 -Dbuild.env=d8`

### Log in and set an autocomplete URL for block and search app
1. `drush @fsd-d8.local uli`
1. Block settings: http://d8.fs-demo.local/admin/structure/block/manage/federatedsearchpageformblock?destination=/admin/structure/block
1. App settings: http://d8.fs-demo.local/admin/config/search-api-federated-solr/search-app/settings
(Note: if you have content indexed in your local index for lando you can use `http://solr.lndo.site/solr/dsgad8/select`)

### Check out this branch of the module
1. From your host machine, in the project root: `cd src/search_api_federated_solr`
1. Check out `root-863-compute-site-specific-urls`

### Run the update hook
1. `drush @fsd-d8.local uli`

### Confirm the direct url values were respected
1. Browse to the block and app settings pages and confirm that autocomplete is enabled, the autocomplete proxies are disabled, and the url value from before is entered into the text field
    1. Block settings: http://d8.fs-demo.local/admin/structure/block/manage/federatedsearchpageformblock?destination=/admin/structure/block
    1. App settings: http://d8.fs-demo.local/admin/config/search-api-federated-solr/search-app/settings
1. If you used a custom endpoint that has indexed content, try to search from the block and app and see if you get autocomplete results (I used my lando index and saw results)

## To test the computation of the proxy + default direct urls

### Confirm the default direct url is computed and works
1. Browse to the block and app settings pages and disable the proxy (remember there are 2 on search app settings page), but leave the direct url empty (this should fall back to the solr backend automatically)
    1. Block settings: http://d8.fs-demo.local/admin/structure/block/manage/federatedsearchpageformblock?destination=/admin/structure/block
    1. App settings: http://d8.fs-demo.local/admin/config/search-api-federated-solr/search-app/settings
1. Search from the block and app and see confirm you get autocomplete results + regular results on search

### Confirm the proxy urls work
1. Browse to the block and app settings pages and enable the proxies (remember there are 2 on the search app settings page)
    1. Block settings: http://d8.fs-demo.local/admin/structure/block/manage/federatedsearchpageformblock?destination=/admin/structure/block
    1. App settings: http://d8.fs-demo.local/admin/config/search-api-federated-solr/search-app/settings
1. Search from the block and app and see confirm you get autocomplete results + regular results on search

2019-03-28 21:28 UTC, jesconstantine commented on src/Controller/SearchController.php
> +  private function get_server_url($index_id) {
Should I create a utility or helpers class with this function since we pretty much use it more than once?

2019-03-28 22:03 UTC, agentrickard commented on src/Controller/SearchController.php
> +  private function get_server_url($index_id) {
I would think so.

2019-03-29 13:44 UTC, agentrickard commented
There is still something very odd about the branches / checkouts here. I don't see our fix to the terms indexing issue when I `git checkout 8.x-2.0` nor when I `git checkout origin/8.x-2.x` nor 'git checkout composer/8.x-2.x`.

For instance:

`git checkout 8.x-2.0`
`HEAD is now at ea8fb10... Merge pull request #77 from palantirnet/features/d8/root-198-autocomplete-config`

```
        // If there are no taxonomy terms on this $entity, do nothing.
        if (empty($entity_terms)) {
          return;
        }
```

That `return` should be a `continue`.

2019-03-29 14:16 UTC, jesconstantine commented on src/Controller/SearchController.php
> +  private function get_server_url($index_id) {
Added in https://github.com/palantirnet/search_api_federated_solr/pull/83/commits/adae3cb504fca78fb2ae4fc0801f9495cd35b0a4 and https://github.com/palantirnet/search_api_federated_solr/pull/83/commits/30ef044c32b3944eca9eee880127d69029bf0ef6

2019-03-29 15:28 UTC, agentrickard requested changes

2019-03-29 15:28 UTC, agentrickard commented on README.md
> +    - Set `$config['search_api_federated_solr.search_app.settings']['index']['query_fields']` to an array of _Fulltext_ field machine names (i.e. `['rendered_item', 'full_text_title']`) from your sea
Isn't this step optional? Won't we use defaults if this is not set?

2019-03-29 15:28 UTC, agentrickard commented on config/install/search_api_federated_solr.search_app.settings.yml
> +  query_fields: []
Should we set these to our defaults?

2019-03-29 15:28 UTC, agentrickard commented on src/Controller/SearchController.php
> +    $server_url = $server['scheme'] . '://' . $server['host'] . ':' . $server['port'];
SearchAPI should have a method for computing this value. This was something I recently fixed in the 7.x branch.

2019-03-29 15:28 UTC, agentrickard commented on src/Controller/SearchController.php
> +  private function get_endpoint($proxy_is_disabled, $direct_url, $index_id) {
Here and above, why are the method names using snake case?

2019-03-29 15:28 UTC, agentrickard commented on src/Controller/SearchController.php
> +    } else {
newline

2019-03-29 15:28 UTC, agentrickard commented on src/Controller/SearchController.php
> +   * Returns a content for a search page.
"content" not "a content"

2019-03-29 15:28 UTC, agentrickard commented on src/Plugin/Block/FederatedSearchPageFormBlock.php
> +  private function get_server_url($index_id) {
getServerUrl

2019-03-29 15:28 UTC, agentrickard commented on src/Plugin/Block/FederatedSearchPageFormBlock.php
> +  private function get_autocomplete_url($proxy_is_disabled, $direct_url) {
getAutocompleteUrl 

I can also see cases where these _might_ need to be public methods, if someone is overriding our services.

2019-03-29 15:34 UTC, jesconstantine commented on README.md
> +    - Set `$config['search_api_federated_solr.search_app.settings']['index']['query_fields']` to an array of _Fulltext_ field machine names (i.e. `['rendered_item', 'full_text_title']`) from your sea
The step is not optional, but the method is.  I think the step is not optional because the `search_api` module has solr config default field set as `content`, which does not fit in to our schema.

2019-03-29 15:35 UTC, jesconstantine commented on config/install/search_api_federated_solr.search_app.settings.yml
> +  query_fields: []
That's a good idea!  We could set to `rendered_item`.

2019-03-29 15:36 UTC, jesconstantine commented on README.md
> +    - Set `$config['search_api_federated_solr.search_app.settings']['index']['query_fields']` to an array of _Fulltext_ field machine names (i.e. `['rendered_item', 'full_text_title']`) from your sea
If we set the default to `rendered_item` in the install config (and the update hook?) then this step becomes optional.

2019-03-29 15:39 UTC, jesconstantine commented on src/Controller/SearchController.php
> +  private function get_endpoint($proxy_is_disabled, $direct_url, $index_id) {
Noob mistake.  I'll fix them. :)

2019-03-29 15:40 UTC, agentrickard commented on README.md
> +    - Set `$config['search_api_federated_solr.search_app.settings']['index']['query_fields']` to an array of _Fulltext_ field machine names (i.e. `['rendered_item', 'full_text_title']`) from your sea
I thought our code used some defaults if none were set here?

2019-03-29 15:41 UTC, agentrickard commented on config/install/search_api_federated_solr.search_app.settings.yml
> +  query_fields: []
++

2019-03-29 15:47 UTC, jesconstantine commented on src/Controller/SearchController.php
> +    $server_url = $server['scheme'] . '://' . $server['host'] . ':' . $server['port'];
I thought the same thing.  I couldn't find the url for the select handler, but here's what I did find:

Server Link:
```php
/** @var \Drupal\search_api_solr\SolrConnectorInterface $connector */
$connector->getServerLink(); // http://federated-search-demo.local:8983/solr/
```

Core Link:
```php
/** @var \Drupal\search_api_solr\SolrConnectorInterface $connector */
$connector->getCoreLink(); // http://federated-search-demo.local:8983/solr/#/drupal8
```

We want: `http://federated-search-demo.local:8983/solr/drupal8/select`

So we could get the core from config and just append `$core . '/select'`?

2019-03-29 16:13 UTC, jesconstantine commented on src/Controller/SearchController.php
> +  private function get_endpoint($proxy_is_disabled, $direct_url, $index_id) {
Fixed in https://github.com/palantirnet/search_api_federated_solr/pull/83/commits/170a4681f8877e5c580b8c53801a948d10bc1114

2019-03-29 16:14 UTC, jesconstantine commented on src/Plugin/Block/FederatedSearchPageFormBlock.php
> +  private function get_server_url($index_id) {
This method shouldn't exist any more because they've moved to the module Utility/Helpers class.  But the case has been fixed there as well.  See Fixed in https://github.com/palantirnet/search_api_federated_solr/pull/83/commits/170a4681f8877e5c580b8c53801a948d10bc1114

2019-03-29 16:14 UTC, jesconstantine commented on src/Plugin/Block/FederatedSearchPageFormBlock.php
> +  private function get_autocomplete_url($proxy_is_disabled, $direct_url) {
This method shouldn't exist any more because they've moved to the module Utility/Helpers class.  But the case has been fixed there as well.  See Fixed in https://github.com/palantirnet/search_api_federated_solr/pull/83/commits/170a4681f8877e5c580b8c53801a948d10bc1114

2019-03-29 16:16 UTC, jesconstantine commented on src/Controller/SearchController.php
> +    } else {
Fixed in https://github.com/palantirnet/search_api_federated_solr/pull/83/commits/5acf911c37f87d75e5b149de73d7cbb91d0cb3c7

2019-03-29 16:16 UTC, jesconstantine commented on src/Controller/SearchController.php
> +   * Returns a content for a search page.
Fixed in https://github.com/palantirnet/search_api_federated_solr/pull/83/commits/5acf911c37f87d75e5b149de73d7cbb91d0cb3c7

2019-03-29 16:26 UTC, agentrickard commented on src/Controller/SearchController.php
> +    $server_url = $server['scheme'] . '://' . $server['host'] . ':' . $server['port'];
Yes. That's essentially what I do in D7.

2019-03-29 16:27 UTC, jesconstantine commented on src/Controller/SearchController.php
> +    $server_url = $server['scheme'] . '://' . $server['host'] . ':' . $server['port'];
Ok, updating now.

2019-03-29 16:39 UTC, jesconstantine commented on src/Controller/SearchController.php
> +    $server_url = $server['scheme'] . '://' . $server['host'] . ':' . $server['port'];
Updated in https://github.com/palantirnet/search_api_federated_solr/pull/83/commits/36b8cbfa38dc00099695e6da2dfc135350ed7d0d

2019-03-29 16:39 UTC, jesconstantine commented on config/install/search_api_federated_solr.search_app.settings.yml
> +  query_fields: []
Set in the install config (but not update hook, we should respect work that might have been done since 2.0) in https://github.com/palantirnet/search_api_federated_solr/pull/83/commits/a806161124af85544512caee5b73f8aaeed0434e

2019-03-29 16:42 UTC, jesconstantine commented on README.md
> +    - Set `$config['search_api_federated_solr.search_app.settings']['index']['query_fields']` to an array of _Fulltext_ field machine names (i.e. `['rendered_item', 'full_text_title']`) from your sea
The search app blindly set the query field as `render_item`, but we removed that and in 2.0 the module relies solely on solr config.  

As of https://github.com/palantirnet/search_api_federated_solr/commit/a806161124af85544512caee5b73f8aaeed0434e we'll set one for new installs but I didn't do anything in the update hook (I didn't want to trump any work that might have been done to solr config for folks).

2019-03-29 17:02 UTC, agentrickard commented on src/Utility/Helpers.php
> +  public static function parse_str_multiple($str) {
Snake case...

2019-03-29 17:10 UTC, jesconstantine commented on src/Utility/Helpers.php
> +  public static function parse_str_multiple($str) {
Ah! Thanks for catching.  Fixed in https://github.com/palantirnet/search_api_federated_solr/pull/83/commits/8678fe0b49bc01673913ca8daa5b936849bf5b3b

2019-03-29 17:12 UTC, agentrickard approved these changes

2019-03-29 17:15 UTC, merged